travis:
  secure:
    BINSTAR_TOKEN: sbK2FNGMsvKKUCMoLD1bfqcQ9miVb34RZvJ9ldsMCc9HjOtVIARFji5farvW4FO8eaDHRd4vnfj2t0ybusryzMh1NF3LYXeQVFG/UeNmHbCiSFmSPJsLWVJikORGfAdDYh979ugrBLBXR3MTD+0t5kGapoAJkJvH7e4iASIZK8r6rRzguHTal9ND1MyQ1We6FS5RNFDzhZvyLKIDgva1Dj/Zb6vzKHK4UEcRJhZI2WJitwhkn692KvGyI52X2b/3mKgu0ggyOHHz4DTIFxQ3SjZAzMW+vaU+Opoa5QIeC5pYpermVrur371xPJw0/CnsYWxOdUBIVxE17yoxSOSJfNRkZf5ExsArOuVwWWZGr24B1DJD4SPZpmOm78hN+iF9MpkpS4SGzNwI+SZyncM4CH2JS0TTEI8U0wZ/Dnz8P/MUBIY62SKEneFmVDHFb1xQO5nKx0AcG7XHpKv4ykkr0xTL4bFRIYUZ6POtiS4sUYoTRublbNFr13/bp7JJwrj5xZ5V4OouA8PsrXlVSY1Se3j6fnIQ2BZZS98xMZLtgQXLK6a8Q8SWXweFrKy7ZsywXrDedzffMdXjL0aXqUbA0PwFWBvHc8zLsin8djjhBNGHLa6lDVVwUoAfjL1ZNXLFKWRK7gO6SgWMAjJ2OWrfuyq5Fkm8CgCPrLVH1WUjyTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
